[colors]
background = "#1f1f1fFF"
text_primary = "#e2e2e2FF"
text_muted = "#c6c6c6FF"
accent_primary = "#aac7ffFF"
accent_secondary = "#bec6dcFF"
warning = "#dcbce0FF"
error = "#ffb4abFF"
insert_hint = "#dcbce080"
backdrop = "#474747FF"

[colors.border]
focused = "#aac7ffFF"
unfocused = "#474747FF"
scratchpad_focused = "#dcbce0FF"
scratchpad_unfocused = "#573e5cFF"
outer = "#131313FF"

[colors.overview]
background_tint = "#13131388"
badge = "#aac7ffFF"
workspace_background = "#131313FF"
