[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.cursor]
text = '#131313'
cursor = '#e2e2e2'

[colors.vi_mode_cursor]
text = '#131313'
cursor = '#e9c348'

[colors.search.matches]
foreground = '#474747'
background = '#accfae'

[colors.search.focused_match]
foreground = '#474747'
background = '#e9c348'

[colors.footer_bar]
foreground = '#474747'
background = '#e2e2e2'

[colors.hints.start]
foreground = '#474747'
background = '#d4c5a1'

[colors.hints.end]
foreground = '#474747'
background = '#d4c5a1'

[colors.selection]
text = '#c6c6c6'
background = '#474747'


[colors.normal]
black   = '#474747'
red     = '#ffb4ab'
green   = '#e9c348'
yellow  = '#d4c5a1'
blue    = '#accfae'
magenta = '#e9c348'
cyan    = '#d4c5a1'
white   = '#e2e2e2'


[colors.bright]
black   = '#919191'
red     = '#ffb4ab'
green   = '#e9c348'
yellow  = '#d4c5a1'
blue    = '#accfae'
magenta = '#e9c348'
cyan    = '#d4c5a1'
white   = '#e2e2e2'


[colors.dim]
black   = '#474747'
red     = '#ffb4ab'
green   = '#e9c348'
yellow  = '#d4c5a1'
blue    = '#accfae'
magenta = '#e9c348'
cyan    = '#d4c5a1'
white   = '#e2e2e2'
