include themes/noctalia.conf


# BEGIN_KITTY_FONTS
font_family      family='JetBrains Mono' postscript_name=JetBrainsMono-Light
bold_font        family='JetBrains Mono' postscript_name=JetBrainsMono-Light
italic_font      family='JetBrains Mono' postscript_name=JetBrainsMono-Light
bold_italic_font family='JetBrains Mono' postscript_name=JetBrainsMono-Light

font_size 12
window_margin_width 10
sync_to_monitor yes
input_delay 3
hide_window_decorations no
# END_KITTY_FONTS
